{% set name = "genespeak" %}
{% set version = "0.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/genespeak-{{ version }}.tar.gz
  sha256: b17f06171e17f541289e1df7eca8c70a29bdfcf1862c5be98e2e694788bb8f65

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - genespeak
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sugatoray/genespeak/
  summary: A library to encode text as DNA and decode DNA to text.
  license: MIT
  license_file: LICENSE
  description: |
    ![genespeak-banner][#repo-banner]

    [#repo-banner]: https://raw.githubusercontent.com/sugatoray/genespeak/master/docs/assets/images/genespeak_banner_01.png
    
    GeneSpeak allows you to encode regular text as DNA using 
    base-pairs (`A`, `C`, `G`, `T`) and convert back to the 
    original text. Text encoding is done for both `ascii` and 
    `utf-8` characters based on the `strategy` keyword argument.

    PyPI: [https://pypi.org/project/genespeak/](https://pypi.org/project/genespeak/)

  doc_url: https://sugatoray.github.io/genespeak/
  dev_url: https://github.com/sugatoray/genespeak/

extra:
  recipe-maintainers:
    - sugatoray
